// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc6408.CogBot.subsystems;

import org.usfirst.frc6408.CogBot.Robot;
import org.usfirst.frc6408.CogBot.RobotMap;
import org.usfirst.frc6408.CogBot.commands.*;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Subsystem;

//TODO: Finished
public class DriveTrain extends Subsystem {
	public float speed = 0.5f;  //holds the speed value
	public RobotDrive drive = new RobotDrive(0, 1, 2, 3);

    public void initDefaultCommand() {
    	
    }
    
    public void driveMotors(double leftSpeed, double rightSpeed) 
    {
    	Robot.driveTrain.drive.setLeftRightMotorOutputs(leftSpeed, rightSpeed);
    }
    
    public void driveDirection (double ySpeed, double xSpeed) {  //Drives the robot in teleop.
    	drive.setLeftRightMotorOutputs (  //Moving the joy on the x turns the robot and turning it on the y moves back and forth
    			(ySpeed - (xSpeed / 2)) * speed, 
    			(ySpeed + (xSpeed / 2)) * speed
    	); 
    }
}

