// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc6408.CogBot.subsystems;

import org.usfirst.frc6408.CogBot.Robot;
import org.usfirst.frc6408.CogBot.RobotMap;
import org.usfirst.frc6408.CogBot.commands.*;
import org.w3c.dom.css.ElementCSSInlineStyle;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Subsystem;

//TODO: Finished
public class DriveTrain extends Subsystem {
	public double speed = 0.5;  //holds the speed value
	public RobotDrive drive = new RobotDrive(0, 1, 2, 3);
	public int isNegitave = 1;

    public void initDefaultCommand() {
    	
    }
    
    public void driveMotors(double leftSpeed, double rightSpeed) {
    	Robot.driveTrain.drive.setLeftRightMotorOutputs(leftSpeed, rightSpeed);
    }
    
    public void driveDirection (double ySpeed, double xSpeed) {  //Drives the robot in teleop.
    	double ySpeed2 = 0;
    	double xSpeed2 = 0;
    	
    	if(ySpeed <= 0)
    		ySpeed2 = -ySpeed;
    	else
    		ySpeed2 = ySpeed;
    	
    	if(xSpeed <= 0)
    		xSpeed2 = -xSpeed;
    	else
    		xSpeed2 = xSpeed;
    	
    	if(ySpeed2 >= xSpeed2) {
    		drive.setLeftRightMotorOutputs (ySpeed * speed * isNegitave * 1.22, ySpeed * speed * isNegitave); 
    	}
    	else {
    		drive.setLeftRightMotorOutputs (xSpeed * speed / 1.12 * 1.5 * 1.22, -xSpeed * speed / 1.12 * 1.5);
    	}
    }
}

