// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc6408.CogBot.subsystems;

import org.usfirst.frc6408.CogBot.RobotMap;
import org.usfirst.frc6408.CogBot.commands.*;

import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.command.Subsystem;

//TODO: Finished
public class Encoders extends Subsystem {
	public Encoder encL = new Encoder(0, 1, true, EncodingType.k4X);  //TODO: check backwardsness
	public Encoder encR = new Encoder(2, 3, false, EncodingType.k1X);  //Is on the opposide side as L so it is reversed.
	
	public Encoders () {
		encL.setDistancePerPulse(1);
        encR.setDistancePerPulse(1);
		resetEncoders();  //Resets encoders on startup.
	}
	
    public void initDefaultCommand() {
    }
    
    public void resetEncoders () {
    	encL.reset();
    	encR.reset();
    }
    
    public double getAverageDistance() {
    	//Equation is: average of the distances -> converted to rotations -> converted to inches. (Each rotation is 19in.)
    	//System.out.println(encL.getDistance() + encR.getDistance() / 2 / 360 * 19);
    	return (encL.getDistance() + encR.getDistance()) / 2 / 360 * 19; 
    }
    
    public double getLeftEncoder() {
    	//System.out.println(encL.getDistance() / 360 * 19 + " inches.");
    	return encL.getDistance() / 360 * 19;
    }
    
    public double getRightEncoder() {
    	//System.out.println(encL.getDistance() / 360 * 19 + " inches.");
    	return encR.getDistance() / 360 * 19;
    }
    
    public double getLeftEncoderInRotations() {
    	//System.out.println(encL.getDistance() / 360 + " rotations.");
    	return encL.getDistance() / 360;
    }
    
    public double getRightEncoderInRotations() {
    	//System.out.println(encL.getDistance() / 360 + " rotations.");
    	return encR.getDistance() / 360;
    }
}

