// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc6408.CogBot.subsystems;

import org.usfirst.frc6408.CogBot.RobotMap;
import org.usfirst.frc6408.CogBot.commands.*;

import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.RobotDrive.MotorType;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

//TODO: Finished probably?
public class Winch extends Subsystem {
	//The two motors in the CIM
	public SpeedController winchSpeedControllerR = new Spark(8);
	public SpeedController winchSpeedControllerL = new Spark(9);

	public Winch () 
	{
		//I dunno what this does but it was here in the autogen scripts so i'm keeping it.
    	LiveWindow.addActuator("Winch", "Winch Speed Controller R", (Spark) winchSpeedControllerR);
    	LiveWindow.addActuator("Winch", "Winch Speed Controller L", (Spark) winchSpeedControllerL);
	}
	
    public void initDefaultCommand() 
    {
    }
    
    public void turnWinch (int percent)  //set percent to 0 to stop the motors.
    {
    	//Moves the motors
    	winchSpeedControllerR.set(percent);
    	winchSpeedControllerL.set(percent);
    }
}

